FROM node:20-alpine

WORKDIR '/app'

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

ARG VPS_HOST
ENV VPS_HOST=$VPS_HOST

ARG DB_NAME
ENV DB_NAME=$DB_NAME

ARG DB_USER
ENV DB_USER=$DB_USER

ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

RUN npm i -g @nestjs/cli
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build
CMD [ "node", "dist/main.js" ]