name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        # options: ['info', 'debug', 'trace']
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        id: vars
        run: echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          name: GPabis/TSP-Backend/tsp-backend
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: VPS_HOST,DB_NAME,DB_PORT,DB_USER,DB_PASSWORD,JWT_SECRET
          dockerfile: Dockerfile
          tags: "latest,${{ steps.vars.outputs.RELEASE_VERSION }}"
      - name: Deploy package to vps
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          envs: GITHUB_USERNAME,GITHUB_TOKEN
          script: |
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull "ghcr.io/gpabis/tsp-backend/tsp-backend:latest"
            docker stop tsp-backend
            docker system prune -f
            docker run --name tsp-backend -d -dit -p 3001:3000 "ghcr.io/gpabis/tsp-backend/tsp-backend:latest"